spring:
  application:
    name: ffmpeg-ffprobe
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB

server:
  port: 8082

external:
  backendcore:
    stt-url: http://localhost:8080/api/ai/stt/transcribe

logging:
  level:
    com.gdpark: DEBUG

ffmpeg:
  ffmpeg-path: /opt/homebrew/bin/ffmpeg
  ffprobe-path: /opt/homebrew/bin/ffprobe
  work-dir: ./out

vosk:
  model-path: vosk-model-small-ko-0.22
